on:
  pull_request:
    branches:
      - [cite-start]dev

jobs: 
  linting:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        [cite-start]python-version: ["3.11"]
    steps:
      - name: Code check
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        usess: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      -name: Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff pytest flask

        -name: Linting running
          run: |
            ruff check app
        -name: Run Pytest 
          run: |
            pytest tests